name: ncov_2019
description: A new Flutter project.

version: 0.0.10+10

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  #  dio: 2.2.2  #低于Flutter-1.17使用此版本
  dio: ^3.0.9
  nav_router: ^0.0.5
  webview_flutter: ^0.3.12
  device_info: ^0.4.0+1
  package_info: ^0.4.0+6
  pull_to_refresh: ^1.5.6
  flutter_swiper: ^1.1.6
#  cached_network_image: ^1.1.1 # ^1.9.0左右flutter版本的用这个
  cached_network_image: ^2.0.0 # ^2.0.0左右flutter版本直接用这个
  shared_preferences: ^0.5.2+2
  intl: ^0.16.1
  open_file: ^2.1.1
  url_launcher: ^5.2.7
  connectivity: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/bottom_home.png
    - assets/images/bottom_rumor.png
    - assets/images/bottom_protect.png
    - assets/images/bottom_lore.png
    - assets/images/entries_1.png
    - assets/images/entries_2.png
    - assets/images/entries_3.png
    - assets/images/entries_4.png
    - assets/images/entries_5.png
